# Site settings
title: Pedro Ivan Lopez
author: Pedro Ivan Lopez
email: m@pedroivanlopez.com
openpgp_fingerprint: '7E7B 148F FA0F 101A 2506 D3AD C1FB 65BC 220B 9160'
description: > # this means to ignore newlines until "baseurl:"
  Pedro Ivan Lopez's website.
twitter_username: lopezpdvn
github_username:  lopezpdvn
facebook_username: dreilopz
timezone: America/Monterrey
bitcoin_main_address: "1NspYfQDQFivQk5GA2jzTsN2HaEsPYxdEZ"

permalink: "pretty"
#permalink: "/blog/:year/:month/:title"
permalink: "/:title"
images_dir: "images"
statement_org_ideas: >
  The ideas expressed on this website do not necessarily represent the opinion
  of my employer or any other organization.
include: [_images, _modules, _sources, _static, resume.pdf, business_card.pdf]

remote_theme: pages-themes/midnight@v0.2.0


exclude: [
  gulpfile.js,
  package.json,
  node_modules,
  tmp,
  bin,
  TODO.md,
  business_card,
  resume.docx
]

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pedroivanlopez.com" # the base hostname & protocol for your site

short_intro: "I'm a software engineer interested in social networks and large scale systems"

short_status: ""

anonymous_feedback_form: https://docs.google.com/forms/d/1yh47EqoOpMqcAhTjRjWE4NyTp3r6GfRSBjcCx_9qMqQ/viewform

vcard_url: pedro_ivan_lopez_vcard.vcf

button_img_size: 30

# Build settings
markdown: kramdown

highlight: pygments

# GitHub Pages documentation calls this entry `plugins`.
plugins:
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
    values:
      author: "Pedro Ivan Lopez"

collections:
  ustruct:
    output: true

feed:
  collections:
    ustruct:
      path: "ustruct.xml"
