# Site settings
title: Pedro Ivan Lopez's website
author: Pedro Ivan Lopez
email: m@pedroivanlopez.com
description: > # this means to ignore newlines until "baseurl:"
  Pedro Ivan Lopez's website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pedroivanlopez.com" # the base hostname & protocol for your site
#keep_files: ["printer73x/doc"]
#exclude: ["printer73x/doc"]
include: [_images, _modules, _sources, _static]
twitter_username: dreilopz
github_username:  lopezpdvn
timezone: America/Monterrey
permalink: "pretty"
#permalink: "/blog/:year/:month/:title"
permalink: "/:title"
images_dir: "images"
bitcoin_main_address: "121PXBqUyuvEqu4siiu7EHUU68kj87Bdfg"
statement_org_ideas: >
  The ideas expressed in this website do not necessarily represent the opinion
  of my employer or any other organization.

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      author: "Pedro Ivan Lopez"
